### PR TITLE
Put null check before any use of canvas in onRenderSceneControls

### PR DESCRIPTION
**Pull request by wickermoon**
- Rename name to id (which v10 apparently wants) in module.json

See #79

### CODE REVIEW

**Comment by cas206** [comment]
Noticed same issue.  I tracked it down to the deactivate() function call when canvas['lockview'] is null.  Should the entire routine be canceled using the proposed solution?  Or just the deactivate() function call?
```
 if (compatibleCore('10.0') && controls.activeControls != 'LockView') 
      canvas['lockview'].deactivate();
```

**Comment by wickermoon** [comment]
I updated the module.json. I tested it and it seems like foundry doesn't care whether both exist at the same time. It doesn't even produce a warning, which is nice!

**Comment by wickermoon** [comment]
> Noticed same issue. I tracked it down to the deactivate() function call when canvas['lockview'] is null. Should the entire routine be canceled using the proposed solution? Or just the deactivate() function call?
> 
> ```
>  if (compatibleCore('10.0') && controls.activeControls != 'LockView') 
>       canvas['lockview'].deactivate();
> ```

The whole function doesn't make sense, if canvas is null. Also, the null check was in before, just further down the function, after canvas was already used. So if anything, deactivate should the only thing to be called, which is impossible, because canvas is null. Maybe the combatTrigger could still be set, since it doesn't require the canvas, but I don't think it makes sense to execute anything from that function when canvas is null.

**Comment by wickermoon** [comment]
Okay, I did some refactoring. Just in case, I tested the function and it still works just as before. If you want, I can revert those refactoring changes, but it makes the whole function easier to read and understand. :)

**Comment by CDeenen** [comment]
The refactoring is fine :)
It all seems to work fine like this, so I've pushed an update. Thanks for the help!

**Pull request merged**
